FROM mutable_base

COPY CMakeLists.txt /mutable
RUN rm -rf /mutable/src
COPY src /mutable/src
WORKDIR /mutable

RUN rm -rf CMakeCache.txt CMakeFiles cmake_install.cmake
RUN ldconfig && cmake . && make -j4



FROM alpine as certs
RUN apk update && apk add ca-certificates



FROM busybox:glibc
COPY --from=certs /etc/ssl/certs /etc/ssl/certs
WORKDIR /root

COPY --from=0 \
    /usr/lib/x86_64-linux-gnu/libssl.so.1.1\
    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 \
    /usr/local/lib/libmongocxx.so._noabi \
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
    /lib/x86_64-linux-gnu/libgcc_s.so.1 \
    /lib/x86_64-linux-gnu/libdl.so.2 \
    /usr/local/lib/libbsoncxx.so._noabi \
    /usr/local/lib/libmongoc-1.0.so.0 \
    /usr/local/lib/libbson-1.0.so.0 \
    /usr/lib/x86_64-linux-gnu/libsasl2.so.2 \
    /lib/x86_64-linux-gnu/librt.so.1 \
    /lib/x86_64-linux-gnu/libz.so.1 \
    /usr/local/lib/libcppkafka.so.0.3.1 \
    /usr/local/lib/librdkafka.so.1 \
    /usr/lib/x86_64-linux-gnu/libzstd.so.1 \
    /usr/lib/x86_64-linux-gnu/liblz4.so.1 \
    /usr/local/lib/libhiredis.so.0.14 \
    /usr/local/lib/libredis++.so \
    /usr/lib/x86_64-linux-gnu/libpq.so.5 \
    /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20 \
    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 \
    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 \
    /usr/lib/x86_64-linux-gnu/libkrb5.so.3 \
    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 \
    /lib/x86_64-linux-gnu/libcom_err.so.2 \
    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 \
    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 \
    /usr/lib/x86_64-linux-gnu/libgssapi.so.3 \
    /usr/lib/x86_64-linux-gnu/libgnutls.so.30 \
    /lib/x86_64-linux-gnu/libkeyutils.so.1 \
    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 \
    /usr/lib/x86_64-linux-gnu/libkrb5.so.26 \
    /usr/lib/x86_64-linux-gnu/libasn1.so.8 \
    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 \
    /usr/lib/x86_64-linux-gnu/libroken.so.18 \
    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 \
    /usr/lib/x86_64-linux-gnu/libidn2.so.0 \
    /usr/lib/x86_64-linux-gnu/libunistring.so.2 \
    /usr/lib/x86_64-linux-gnu/libtasn1.so.6 \
    /usr/lib/x86_64-linux-gnu/libnettle.so.6 \
    /usr/lib/x86_64-linux-gnu/libhogweed.so.4 \
    /usr/lib/x86_64-linux-gnu/libgmp.so.10 \
    /usr/lib/x86_64-linux-gnu/libwind.so.0 \
    /usr/lib/x86_64-linux-gnu/libheimbase.so.1 \
    /usr/lib/x86_64-linux-gnu/libhx509.so.5 \
    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 \
    /lib/x86_64-linux-gnu/libcrypt.so.1 \
    /usr/lib/x86_64-linux-gnu/libffi.so.6 \
    /lib/

COPY --from=0 /mutable/build/mutable .

ENTRYPOINT [ "./mutable" ]

