version: 2

jobs:

  build:

    docker:
      - image: "debian:stretch"

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake pkg-config libssl-dev libpqxx-dev'
      - run:
          name: Creating Build Files
          command: 'cmake .'
      - run:
          name: Creating Binary Files
          command: 'make'
#      - run:
#          name: Run Binary
#          command: './build/mutable'

