version: 2

jobs:

  build:

    docker:
      - image: "ubuntu:bionic"

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake pkg-config git libssl-dev libpq-dev libsasl2-dev python libmysqlcppconn-dev libmysqlclient-dev'
      - run:
          name: Update submodules
          command: 'git submodule update --init --recursive'
      - run:
          name: Build libmongoc
          command: 'cd lib/libmongoc && python build/calc_release_version.py > VERSION_CURRENT && mkdir cmake-build && cd cmake-build && cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .. && sudo make -j4 install && cd ../../..'
      - run:
          name: Build mongocxx
          command: 'cd lib/mongocxx-driver/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local && sudo make -j4 install && cd ../../..'
      - run:
          name: Build pqxx
          command: 'cd lib/libpqxx && mkdir build && cmake -DPostgreSQL_TYPE_INCLUDE_DIR:STRING=/usr/include/postgresql .. && sudo make -j4 install && cd ../../..'
      - run:
          name: Creating Build Files
          command: 'cmake .'
      - run:
          name: Creating Binary Files
          command: 'make -j4'
#      - run:
#          name: Run Binary
#          command: './build/mutable'
